services:
  comic-downloader:
    image: ghcr.io/cloudcranesss/comic-downloader:${APP_VERSION:-latest}
    container_name: comic-downloader
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
      DATA_DIR: /app/data
      REDIS_HOST: ""
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      JM_USERNAME: ""
      JM_PASSWORD: ""
    volumes:
      - app_data:/app/data
      - ./downloads:/app/downloads
    restart: unless-stopped

volumes:
  app_data:
